### ISSUE TITLE
Implement installation profile.

### ISSUE THREAD

**Issue by drupalAM** [drupalAM/drupal-am#6]
To make onboarding as simple as possible I recommend to use custom installation profile.
Possible profile name: drupal_am

**Comment by arthurbaghdasar** [comment]
Istallation profile worked for me.

**Comment by arthurbaghdasar** [comment]
Here is an error stored in php error log

[26-Oct-2017 13:42:18 Asia/Yerevan] Recoverable fatal error: Argument 1 passed to Drupal\block\BlockViewBuilder::view() must implement interface Drupal\Core\Entity\EntityInterface, null given, called in C:\wamp\www\drupal-am\themes\drupalam\drupalam.theme on line 18 and defined in C:\wamp\www\drupal-am\core\modules\block\src\BlockViewBuilder.php on line 70 #0 C:\wamp\www\drupal-am\core\includes\bootstrap.inc(566): _drupal_error_handler_real(4096, 'Argument 1 pass...', 'C:\\wamp\\www\\dru...', 70, Array)
#1 C:\wamp\www\drupal-am\core\modules\block\src\BlockViewBuilder.php(70): _drupal_error_handler(4096, 'Argument 1 pass...', 'C:\\wamp\\www\\dru...', 70, Array)
#2 C:\wamp\www\drupal-am\themes\drupalam\drupalam.theme(18): Drupal\block\BlockViewBuilder->view(NULL)
#3 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Theme\ThemeManager.php(287): drupalam_preprocess_page(Array, 'page', Array)
#4 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(435): Drupal\Core\Theme\ThemeManager->render('page', Array)
#5 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#6 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Template\TwigExtension.php(490): Drupal\Core\Render\Renderer->render(Array)
#7 C:\wamp\www\drupal-am\sites\default\files\php\twig\59f1998751352_html.html.twig_DXcQnM9jtW0SuBngQF4X9Itp-\64lYfN2zYjYD7feB4WKqkC4I5WVVuEEKdQDTRRTuWVY.php(90): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#8 C:\wamp\www\drupal-am\vendor\twig\twig\lib\Twig\Template.php(379): __TwigTemplate_a91b2f39144707c997da88f047a43676a2057bc987d42bca1cb7da0cbd4d36e1->doDisplay(Array, Array)
#9 C:\wamp\www\drupal-am\vendor\twig\twig\lib\Twig\Template.php(347): Twig_Template->displayWithErrorHandling(Array, Array)
#10 C:\wamp\www\drupal-am\vendor\twig\twig\lib\Twig\Template.php(358): Twig_Template->display(Array)
#11 C:\wamp\www\drupal-am\core\themes\engines\twig\twig.engine(64): Twig_Template->render(Array)
#12 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Theme\ThemeManager.php(384): twig_render_template('themes/bootstra...', Array)
#13 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(435): Drupal\Core\Theme\ThemeManager->render('html', Array)
#14 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#15 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render(Array)
#16 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(574): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#17 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#18 C:\wamp\www\drupal-am\core\lib\Drupal\Core\EventSubscriber\MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#19 C:\wamp\www\drupal-am\core\lib\Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher.php(111): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#20 C:\wamp\www\drupal-am\vendor\symfony\http-kernel\HttpKernel.php(149): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#21 C:\wamp\www\drupal-am\vendor\symfony\http-kernel\HttpKernel.php(64): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#22 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\ReverseProxyMiddleware.php(47): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 C:\wamp\www\drupal-am\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 C:\wamp\www\drupal-am\core\lib\Drupal\Core\DrupalKernel.php(656): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 C:\wamp\www\drupal-am\index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#29 {main}

[26-Oct-2017 13:43:22 Asia/Yerevan] Recoverable fatal error: Argument 1 passed to Drupal\block\BlockViewBuilder::view() must implement interface Drupal\Core\Entity\EntityInterface, null given, called in C:\wamp\www\drupal-am\themes\drupalam\drupalam.theme on line 18 and defined in C:\wamp\www\drupal-am\core\modules\block\src\BlockViewBuilder.php on line 70 #0 C:\wamp\www\drupal-am\core\includes\bootstrap.inc(566): _drupal_error_handler_real(4096, 'Argument 1 pass...', 'C:\\wamp\\www\\dru...', 70, Array)
#1 C:\wamp\www\drupal-am\core\modules\block\src\BlockViewBuilder.php(70): _drupal_error_handler(4096, 'Argument 1 pass...', 'C:\\wamp\\www\\dru...', 70, Array)
#2 C:\wamp\www\drupal-am\themes\drupalam\drupalam.theme(18): Drupal\block\BlockViewBuilder->view(NULL)
#3 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Theme\ThemeManager.php(287): drupalam_preprocess_page(Array, 'page', Array)
#4 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(435): Drupal\Core\Theme\ThemeManager->render('page', Array)
#5 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#6 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Template\TwigExtension.php(490): Drupal\Core\Render\Renderer->render(Array)
#7 C:\wamp\www\drupal-am\sites\default\files\php\twig\59f1998751352_html.html.twig_DXcQnM9jtW0SuBngQF4X9Itp-\64lYfN2zYjYD7feB4WKqkC4I5WVVuEEKdQDTRRTuWVY.php(90): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#8 C:\wamp\www\drupal-am\vendor\twig\twig\lib\Twig\Template.php(379): __TwigTemplate_a91b2f39144707c997da88f047a43676a2057bc987d42bca1cb7da0cbd4d36e1->doDisplay(Array, Array)
#9 C:\wamp\www\drupal-am\vendor\twig\twig\lib\Twig\Template.php(347): Twig_Template->displayWithErrorHandling(Array, Array)
#10 C:\wamp\www\drupal-am\vendor\twig\twig\lib\Twig\Template.php(358): Twig_Template->display(Array)
#11 C:\wamp\www\drupal-am\core\themes\engines\twig\twig.engine(64): Twig_Template->render(Array)
#12 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Theme\ThemeManager.php(384): twig_render_template('themes/bootstra...', Array)
#13 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(435): Drupal\Core\Theme\ThemeManager->render('html', Array)
#14 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#15 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render(Array)
#16 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\Renderer.php(574): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#17 C:\wamp\www\drupal-am\core\lib\Drupal\Core\Render\MainContent\HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#18 C:\wamp\www\drupal-am\core\lib\Drupal\Core\EventSubscriber\MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#19 C:\wamp\www\drupal-am\core\lib\Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher.php(111): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#20 C:\wamp\www\drupal-am\vendor\symfony\http-kernel\HttpKernel.php(149): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#21 C:\wamp\www\drupal-am\vendor\symfony\http-kernel\HttpKernel.php(64): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#22 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\ReverseProxyMiddleware.php(47): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#25 C:\wamp\www\drupal-am\core\lib\Drupal\Core\StackMiddleware\NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#26 C:\wamp\www\drupal-am\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#27 C:\wamp\www\drupal-am\core\lib\Drupal\Core\DrupalKernel.php(656): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#28 C:\wamp\www\drupal-am\index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#29 {main}

**Comment by kpirumyan** [comment]
Implemented and pushed to dev
